CREATE TABLE room (
	room_number VARCHAR(10) UNIQUE NOT NULL PRIMARY KEY,
    patient_id INT UNSIGNED UNIQUE ,
    employee_id INT UNSIGNED UNIQUE,
    CONSTRAINT FOREIGN KEY (patient_id) REFERENCES patient(patient_id)
		ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
		ON DELETE CASCADE ON UPDATE CASCADE
);